### ISSUE TITLE
CI installDependencies.sh

### ISSUE THREAD

**Issue by csacro** [SoPra-Team-17/KI-Client#1]
Im Branch [FeatureCILoggingParser](https://github.com/SoPra-Team-17/KI-Client/tree/FeatureCILoggingParser) wollte ich analog zum Server die Dependencies mit rein machen, allerdings schlägt Install Dependencies fehlt:

```
Run ./installDependencies.sh
/home/runner/work/_temp/4e41c0aa-8132-4bca-9916-a7c3979d31ba.sh: line 1: ./installDependencies.sh: Permission denied
##[error]Process completed with exit code 126.
```

installDependencies.sh hat aber rwxr-xr-x

**Comment by ottojo** [comment]
Im Repo hat das keine execute-permissions.
```bash
git update-index --chmod=+x installDependencies.sh
chmod +x installDependencies.sh
git commit ...
```
[source](https://stackoverflow.com/a/21694391/4162386)

**Comment by csacro** [comment]
Danke
Funktioniert jetzt
