### ISSUE TITLE
Konfigurationsdatei [FA-KI 43]

### ISSUE THREAD

**Issue by csacro** [SoPra-Team-17/KI-Client#6]
Die Parameter des Commandline Interface m¨ussen auch ¨uber eine Konfigurationsdatei
konfigurierbar sein.

Abhängigkeiten: #5

**Comment by csacro** [comment]
Im Lastenheft steht:
> Optional: ¨Uber eine Konfigurationsdatei oder Kommandozeilenargumente k¨onnen verschiedene Intelligenzstufen oder Strategien f¨ur die KI eingestellt werden.

Hätte gesagt, dass das über die Kommandozeile reicht.
Sonst brauchen wir für die KI config ja auch nen Editor oder so damit das sinnvoll wäre.

**Comment by authaldo** [comment]
Aus meiner Sicht ist die Kommandozeile da auch vollkommen ausreichend
